ALTER TABLE runs ADD COLUMN IF NOT EXISTS llm_provider_name VARCHAR(100);
ALTER TABLE runs ADD COLUMN IF NOT EXISTS llm_model_identifier VARCHAR(255);
ALTER TABLE runs ADD COLUMN IF NOT EXISTS llm_model_version VARCHAR(120);
